INSERT INTO TBL_USER (ID, U_NAME, U_EMAIL) VALUES(1001,'MD IRFAN', 'IRFAN@GMAIL.COM');
INSERT INTO TBL_USER (ID, U_NAME, U_EMAIL) VALUES(1002,'MD IMRAN', 'IMRAN@GMAIL.COM');
INSERT INTO TBL_USER (ID, U_NAME, U_EMAIL) VALUES(1003,'MD RIZWAN', 'RIZWAN@GMAIL.COM');
INSERT INTO TBL_USER (ID, U_NAME, U_EMAIL) VALUES(1004,'MD ARMAN', 'ARMAN@GMAIL.COM');
INSERT INTO TBL_USER (ID, U_NAME, U_EMAIL) VALUES(1005,'MD GUFRAN', 'GUFRAN@GMAIL.COM');

INSERT INTO TBL_POST VALUES(101, 'FIRST POST', 'THIS IS MY FIRST POST', 1001);
INSERT INTO TBL_POST VALUES(102, 'SECOND POST', 'THIS IS MY SECOND POST', 1001);
INSERT INTO TBL_POST VALUES(103, 'THIRE POST', 'THIS IS MY THIRD POST', 1001);
INSERT INTO TBL_POST VALUES(104, 'FOURTH POST', 'THIS IS MY FOURTH POST', 1001);
INSERT INTO TBL_POST VALUES(105, 'FIRST POST', 'THIS IS MY FIRST POST', 1002);
INSERT INTO TBL_POST VALUES(106, 'SECONE POST', 'THIS IS MY SECOND POST', 1002);
INSERT INTO TBL_POST VALUES(107, 'THIRD POST', 'THIS IS MY THIRD POST', 1002);
INSERT INTO TBL_POST VALUES(108, 'FIRST POST', 'THIS IS MY FIRST POST', 1003);
INSERT INTO TBL_POST VALUES(109, 'FIRST POST', 'THIS IS MY FIRST POST', 1004);
INSERT INTO TBL_POST VALUES(110, 'SECOND POST', 'THIS IS MY SECOND POST', 1004);



